# Generated by Django 5.2.7 on 2025-11-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_profile_details_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(choices=[('ccis', 'College of Computer and Information Sciences'), ('coe', 'College of Engineering'), ('cbt', 'College of Business and Technology'), ('cas', 'College of Arts and Sciences'), ('cte', 'College of Teacher Education')], max_length=50),
        ),
    ]
