# Generated by Django 5.2.7 on 2025-12-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0004_alter_threadpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='thread_images/'),
        ),
    ]
