# Generated by Django 5.2.7 on 2025-12-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_communitygroup_image_alter_communitypost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitygroup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='community_banner_images/'),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='community_post_images/'),
        ),
    ]
